name: auto-PR

on:
  pull_request:
    types: [opened, labeled, unlabeled, closed, review_requested,  edited, synchronize]

jobs:
  request-review:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Request review from WForst-Breeze
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.SHEEP }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
          -d '{"reviewers":["WForst-Breeze"]}'

  add-merge-label:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Add "▲ 合并" label on PR merge
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.SHEEP }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels \
          -d '{"labels":["▲ 合并"]}'

  auto-merge:
    if: contains(github.event.pull_request.labels.*.name, '▲ 合并')
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge PR with "▲ 合并" label
        run: |
          curl -X PUT \
          -H "Authorization: token ${{ secrets.SHEEP }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge

  add-approved-label:
    if: github.event.review.state == 'approved' && github.event.review.user.login == 'WForst-Breeze'
    runs-on: ubuntu-latest
    steps:
      - name: Add "⇵ 通过" label when approved by WForst-Breeze
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.SHEEP }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels \
          -d '{"labels":["⇵ 通过"]}'

  auto-close-pr:
    if: contains(github.event.pull_request.labels.*.name, '× 重新编写') || 
        contains(github.event.pull_request.labels.*.name, '× 无效') || 
        contains(github.event.pull_request.labels.*.name, '× 拒绝')
    runs-on: ubuntu-latest
    steps:
      - name: Close PR if specific labels are added
        run: |
          curl -X PATCH \
          -H "Authorization: token ${{ secrets.SHEEP }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }} \
          -d '{"state":"closed"}'

  add-request-changes-label:
    if: github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest
    steps:
      - name: Add "◈ 修正" label when changes are requested
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.SHEEP }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels \
          -d '{"labels":["◈ 修正"]}'