name: Merge after a pull request is labeled

on:
    pull_request:
        types:
          - labeled

permissions:
    pull-requests: write

jobs:
    label_after_merged:
        if: github.event.pull_request.labels.name == '▲ 合并'
        runs-on: ubuntu-latest
        steps:
            - name: Merge
              run: |
                gh pr merge ${{ github.event.pull_request.number }} -s --admin
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}